version: '3.8'

services:
  # 1. Container cho Database MySQL
  mysql-db:
    image: mysql:8.0
    container_name: hr_database_container
    environment:
      MYSQL_DATABASE: employee_db
      MYSQL_ROOT_PASSWORD: root # Đặt mật khẩu root cho MySQL (bắt buộc phải có)
    ports:
      # Mapping cổng: Ánh xạ cổng 3307 của máy bạn vào cổng 3306 của container 
      # (Dùng 3307 để không bị đụng hàng với MySQL XAMPP đang chạy trên máy bạn)
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql # Tạo ổ cứng ảo để tắt máy không bị mất sạch dữ liệu

  redis-db:
    image: redis:7-alpine
    container_name: hr_redis_container
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hr_phpmyadmin_container
    ports:
      - "8081:80" # Mở cổng 8081 để truy cập phpMyAdmin qua trình duyệt
    environment:
      PMA_HOST: mysql-db # Kết nối phpMyAdmin với MySQL container
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root # Cung cấp mật khẩu root để phpMyAdmin có thể kết nối
    depends_on:
      - mysql-db

  # 2. Container cho Backend Spring Boot của bạn
  backend-app:
    build: . # Bảo Docker nhìn vào file Dockerfile ở thư mục hiện tại để tự build image
    container_name: hr_backend_container
    ports:
      - "8080:8080" # Mở cửa 8080 ra ngoài
    depends_on:
      - mysql-db # Bắt buộc phải chờ mysql-db khởi động xong thì app mới được chạy
      - redis-db
    env_file:
      - .env
    environment:
      # Ghi đè file application.properties bằng biến môi trường!
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/employee_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update # Tự động tạo bảng nếu chưa có
      SPRING_DATA_REDIS_HOST: redis-db
      SPRING_DATA_REDIS_PORT: 6379

volumes:
  db_data: