spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/employee_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# JWT
# Lưu ý: nên dùng chuỗi random dài (>= 64 ký tự cho HS512)
jwt.secret=CHANGE_ME_0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
jwt.expirationMs=86400000

